### ISSUE TITLE
Fehlermeldung wenn man nicht eingeloggt ist

### ISSUE THREAD

**Issue by wubabuba** [wubabuba/lkmtv#1]
Wenn eine Seite aufgerufen wird bei der man eingeloggt sein muss, wird man ohne Kommentar auf die index.php zum einloggen weitergeleitet.

eventuell auch gleich Erfolgsmeldung bei erfolgreichem Ausloggen

**Comment by mkschiller** [comment]
Erledigt --> durch Weiterleiten auf die Login index.php?id=1
Meldung bei Ausloggen nicht nötig --> Änderung der Anzeige oben Rechts
